FROM node:alpine as build-stage

WORKDIR /app

COPY frontend/ /app/
COPY nginx.conf /nginx.conf
COPY .frontend.env /.frontend.env

RUN npm install

# Uncomment to run tests on docker-build
#RUN CI=true npm test

RUN npm run build

# Use nginx image for HTTP routing
FROM nginx:1.15

COPY --from=build-stage /app/build/ /usr/share/nginx/html

COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf